In [1]:
import pandas as pd

In [2]:
PATH_ROAD_CSV = '../../../train/output/open_baseline/resnet34_lr2.00e-04_bs4_16-07-2022-12-15/test/submission.csv'
PATH_BUILD_CSV = '../../../train/output/open_baseline_flood/resnet34_siamese_lr1.00e-04_bs2_16-07-2022-14-19/test/building_submission.csv'

In [3]:
df = pd.read_csv(PATH_ROAD_CSV).rename(columns={'WKT_Pix': 'Wkt_Pix', 'WKT_Geo': 'Wkt_Geo'}, index={})
df = df.append(pd.read_csv(PATH_BUILD_CSV), ignore_index=True)
df.head(3)

,ImageId,Object,Flooded,Wkt_Pix,Wkt_Geo,length_m,travel_time_s
0,104001006504F400_0_0_16,Road,False,"LINESTRING (70 5, 74 7, 76 31)",LINESTRING (29.8872525197028 -90.5129184864106...,10.181899,0.911
1,104001006504F400_0_0_16,Road,False,"LINESTRING (71 212, 77 260, 77 283)",LINESTRING (29.8865756571025 -90.5129152165429...,25.812857,1.650
2,104001006504F400_0_0_16,Road,False,"LINESTRING (73 466, 71 491, 78 523, 72 617, 80...",LINESTRING (29.8857451107234 -90.5129086768077...,281.840652,18.013

In [8]:
df.loc[df['Flooded'] == False, 'Flooded'] = 'Null'
df.head()

,ImageId,Object,Flooded,Wkt_Pix,Wkt_Geo,length_m,travel_time_s
0,104001006504F400_0_0_16,Road,Null,"LINESTRING (70 5, 74 7, 76 31)",LINESTRING (29.8872525197028 -90.5129184864106...,10.181899,0.911
1,104001006504F400_0_0_16,Road,Null,"LINESTRING (71 212, 77 260, 77 283)",LINESTRING (29.8865756571025 -90.5129152165429...,25.812857,1.650
2,104001006504F400_0_0_16,Road,Null,"LINESTRING (73 466, 71 491, 78 523, 72 617, 80...",LINESTRING (29.8857451107234 -90.5129086768077...,281.840652,18.013
3,104001006504F400_0_0_17,Road,Null,"LINESTRING (72 22, 76 39, 75 229)",LINESTRING (29.8829461040284 -90.5129119466754...,75.182900,4.805
4,104001006504F400_0_0_17,Road,Null,"LINESTRING (612 256, 606 261, 582 271, 507 322...",LINESTRING (29.8821809550019 -90.5111462181523...,140.189844,17.920

In [5]:
PATH_SUBMIT_CSV = '../../../submit/open_baseline/solution/solution.csv'
df.to_csv(PATH_SUBMIT_CSV, index=False, header=True)